runtime: python39
env: standard
instance_class: F1

entrypoint: gunicorn -b :$PORT sistema_libros.wsgi

env_variables:
  # Reemplaza YOUR_PASSWORD con tu contraseña real
  MONGODB_URI: "mongodb+srv://kevinmirama2:4PNt6F9JXE9q7hUK@cluster0.1buy3.mongodb.net/sistema_libros?retryWrites=true&w=majority&appName=Cluster0"
  SECRET_KEY: "tu-secret-key-de-django"
  DEBUG: "False"
  ALLOWED_HOSTS: ".appspot.com"

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto

basic_scaling:
  max_instances: 2
  idle_timeout: 10m