runtime: python39
entrypoint: gunicorn sistema_libros.wsgi:application --bind :$PORT --workers 2 --timeout 120

env_variables:
  MONGODB_URI: "mongodb+srv://kevinmirama2:zJUNzXMq34pXuWKv@cluster0.1buy3.mongodb.net/sistema_libros?retryWrites=true&w=majority&appName=Cluster0"
  SECRET_KEY: "django-insecure-mz08!_&3%iv8-(z5g@1v8mook%)auy3)tx(2$r_b$u=ti45o4x"
  DEBUG: "False"
  ALLOWED_HOSTS: ".appspot.com,reto-vacante.rj.r.appspot.com"

handlers:
  # Archivos estáticos
  - url: /static/(.*)
    static_files: staticfiles/\1
    upload: staticfiles/.*
    secure: always

  # Favicon
  - url: /favicon\.ico
    static_files: staticfiles/favicon.ico
    upload: staticfiles/favicon\.ico
    secure: always

  # Todas las demás URLs
  - url: /.*
    script: auto
    secure: always

basic_scaling:
  max_instances: 2
  idle_timeout: 10m