runtime: python39
entrypoint: gunicorn -b :$PORT sistema_libros.wsgi

instance_class: F2

env_variables:
  DJANGO_SECRET_KEY: "django-insecure-mz08!_&3%iv8-(z5g@1v8mook%)auy3)tx(2$r_b$u=ti45o4x"
  MONGODB_URI: "mongodb+srv://kevinmirama2:YGDnmLcmoOi4dDeY@cluster0.1buy3.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  DEBUG: "False"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
