runtime: python39
entrypoint: gunicorn -b :$PORT sistema_libros.wsgi

env_variables:
  MONGODB_URI: "mongodb+srv://kevinmirama2:4PNt6F9JXE9q7hUK@cluster0.1buy3.mongodb.net/sistema_libros?retryWrites=true&w=majority&appName=Cluster0"
  SECRET_KEY: "django-insecure-mz08!_&3%iv8-(z5g@1v8mook%)auy3)tx(2$r_b$u=ti45o4x"
  DEBUG: "False"
  ALLOWED_HOSTS: ".appspot.com"

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto

basic_scaling:
  max_instances: 2
  idle_timeout: 10m

